<Project Sdk="Microsoft.NET.Sdk.Razor">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

 
	<ItemGroup>
		<PackageReference Include="System.Linq.Async" Version="7.0.0" />
		<PackageReference Include="chd.UI.Base.Components" Version="2.0.25327.148" />
		<PackageReference Include="chd.Hub.Base.Client" Version="2.0.25327.148" />
	</ItemGroup>

 
	<ItemGroup>
	  <ProjectReference Include="..\chdScoring.Contracts\chdScoring.Contracts.csproj" />
	  <ProjectReference Include="..\chdScoring.Main.Client\chdScoring.Main.Client.csproj" />
	</ItemGroup>
</Project>
