# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    env:
      BUILD_CONFIG: 'Release'
      SOLUTION: 'chdscoring.sln'
      # VERSION: '1.0'
      
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set Datetime
      id: date
      run: |
        echo "year=$(date +%y%j)" >> $GITHUB_OUTPUT
        echo "hour=$(date +%H%M)" >> $GITHUB_OUTPUT
        
    - name: Install Maui
      run: dotnet workload install maui 
    - name: Define Date Var
      run: echo "DATEVERSION=2.2.${{ steps.date.outputs.year }}.${{ github.run_number }}" >> $GITHUB_ENV
    - name: Write Version
      run: |
        echo ${{env.DATEVERSION}}
        echo "VERSION=${{env.DATEVERSION}}" >> $GITHUB_ENV
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
