# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    env:
      BUILD_CONFIG: 'Release'
      SOLUTION: 'chdscoring.sln'
      VERSION: '1.0.0.0'
      
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set Datetime
      id: date
      run: |
        $YEAR=& Get-Date -UFormat "%y%j"
        echo "year=$YEAR" >> $GITHUB_OUTPUT
        $HOUR=& Get-Date -format HHmm
        echo "hour=$HOUR" >> $GITHUB_OUTPUT
        echo "VERSION=2.2.$YEAR.$HOUR" >> $GITHUB_ENV
        
    - name: Install Maui
      run: dotnet workload install maui 
        
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
