name: Update Version

on:
  workflow_dispatch: # manuell auslösbar
    inputs: 
      package_name:
        description: 'How to build debug/release'
        required: true
        default: 'com.companyname.chd.poomsae.scoring.app'
      platform:
        description: 'How to build debug/release'
        required: true
        default: 'ios'
        
jobs:
  build-ios:
    env:
      BUILD_CONFIG: ${{ github.event.inputs.build_config }}
      
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Publish
      run: |
        $MAJOR=2
        $MINOR=2
        $YEAR=& Get-Date -UFormat "%y%j"
        $HOUR=& Get-Date -format HHmm
        $VERSION="$MAJOR.$MINOR.$YEAR.$HOUR"
        echo $VERSION
        echo "DATEVERSION=$VERSION" >> $env:GITHUB_ENV

    - name: Set up SSH
      run: |
         mkdir -p ~/.ssh
         echo "${{ secrets.SSH_KEY }}" > ~/.ssh/id_ed25519
         chmod 600 ~/.ssh/id_ed25519
         ssh-keyscan github.com >> ~/.ssh/known_hosts
         
    - name: SSH-Key aus Secret speichern
      shell: pwsh
      run: |
        $sshPath = "$env:USERPROFILE\.ssh"
        if (-Not (Test-Path $sshPath)) {
          New-Item -ItemType Directory -Path $sshPath | Out-Null
        }
        $privateKey = '${{ secrets.SSH_KEY }}' -replace "`r`n", "`n"
        $privateKey | Out-File -FilePath "$sshPath\id_ed25519" -Encoding ascii
        icacls "$sshPath\id_ed25519" /inheritance:r /grant:r "${env:USERNAME}:(R,W)"
        # Known hosts hinzufügen, damit SSH-Verbindung klappt
        ssh-keyscan github.com | Out-File -FilePath "$sshPath\known_hosts" -Encoding ascii
    - name: Beispiel git clone via SSH
      run: |
        git clone git@github.com:chridecker/chd.version.git
        cd chd.version
        mkdir -p ${{ github.event.inputs.package_name }}/${{ github.event.inputs.platform }}
        @{Version= $env:DATEVERSION |ConvertTo-Json -Compress > ${{ github.event.inputs.package_name }}/${{ github.event.inputs.platform }}/Version.json
        git add ${{ github.event.inputs.package_name }}/${{ github.event.inputs.platform }}/Version.json
        git config user.name "CHD Build Service"
        git config user.email "chdscoring@gmail.com"
        git commit -a -m "Version $env:DATEVERSION  "
        git push -f     
