name: Update Version

on:
  workflow_dispatch: # manuell auslösbar
    inputs: 
      package_name:
        description: 'How to build debug/release'
        required: true
        default: 'com.companyname.chd.poomsae.scoring.app'
      platform:
        description: 'How to build debug/release'
        required: true
        default: 'ios'
        
jobs:
  build-ios:
    env:
      BUILD_CONFIG: ${{ github.event.inputs.build_config }}
      
    runs-on: macos-15

    steps:
    - uses: actions/checkout@v3

    - name: Set Datetime
      id: date
      run: |
        echo "year=$(date +%y%j)" >> $GITHUB_OUTPUT
        echo "hour=$(date +%H%M)" >> $GITHUB_OUTPUT
    - name: Define Date Var
      run: echo "DATEVERSION=2.2.${{ steps.date.outputs.year }}.${{ steps.date.outputs.hour }}" >> $GITHUB_ENV
    - name: Define Date Var iOS
      run: echo "DATEIOSVERSION=2.${{ steps.date.outputs.year }}.${{ github.run_number }}" >> $GITHUB_ENV

    - name: Set up SSH
      run: |
         mkdir -p ~/.ssh
         echo "${{ secrets.SSH_KEY }}" > ~/.ssh/id_ed25519
         chmod 600 ~/.ssh/id_ed25519
         ssh-keyscan github.com >> ~/.ssh/known_hosts
    
    - name: Update Github Version
      run: |
        git clone git@github.com:chridecker/chd.version.git
        cd chd.version
        ls
        mkdir -p ${{ github.event.inputs.package_name }}/${{ github.event.inputs.platform }}
        ls
        echo "{\"Version\": \"${{ env.DATEIOSVERSION }} \"}" > ${{ github.event.inputs.package_name }}/${{ github.event.inputs.platform }}/Version.json
        git config user.name "CHD Build Service"
        git config user.email "chdscoring@gmail.com"
        git commit -a -m "Version ${{ env.DATEIOSVERSION }} "
        git push -f
